### ISSUE TITLE
menus are in english

### ISSUE THREAD

**Issue by saknl** [flathub/org.tabos.roger#3]
Menus are in English, although the system language is German. I didn't find a way to change the language of roger router.
![Bildschirmfoto von 2020-11-17 16-57-30](https://user-images.githubusercontent.com/61543103/99415298-f35e2a80-28f7-11eb-9bc5-01caf21835f4.png)

**Comment by janbrummer** [comment]
Have you installed the Locale package?

**Comment by saknl** [comment]
Are you referring to org.tabos.roger.Locale?
If so, yes it's installed. I have installed roger router with gnome-software on different fedora installations and this problem always occurs.

**Comment by janbrummer** [comment]
Works fine for me on Fedora 33 and Rawhide include Mobian on Pinephone. 

You can try the following: LANG=de_DE flatpak run org.tabos.roger

**Comment by saknl** [comment]
> Works fine for me on Fedora 33 and Rawhide include Mobian on Pinephone.
> 
> You can try the following: LANG=de_DE flatpak run org.tabos.roger

Thank's for your reply but unfortunately that doesn't change anything.

Actually as you can see in the screenshot, the top bar containing type, date, name and so on is displayed in German no matter if I use `flatpak run org.tabos.roger` or `LANG=de_DE flatpak run org.tabos.roger`. But when I use `LANG=en_US flatpak run org.tabos.roger` the top bar changes to English.
Menus are still always in English. I also tried tu use a fresh Fedora 33 and Ubuntu 20.10 VM and the problem always occurs.

**Comment by janbrummer** [comment]
Now i got you, sorry... fixed in https://gitlab.com/tabos/rogerrouter/-/commit/e5c78a5ffa38236b7a1b465dbd2b9823da4df2d8

**Comment by saknl** [comment]
Great! @janbrummer Thank you for your work!
