### ISSUE TITLE
GNOME Application Platform version

### ISSUE THREAD

**Issue by Suppenlaender** [flathub/org.tabos.roger#8]
A "flatpak update" produce following:

Info: org.gnome.Platform//40 is end-of-life, with reason:
   The GNOME 40 runtime is no longer supported as of March 21, 2022. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   org.tabos.roger

Are there plannings to do compilations with an actually GNOME Application Platform version?

**Comment by janbrummer** [comment]
Closing as obsolete, currently set to 42.
